/**
 * Config generators — pure functions that produce configuration content
 * for each generated file in the scaffolded project.
 *
 * These live in the application layer because they orchestrate domain concepts
 * (project name, runtime, language) into concrete output.
 */

export interface GeneratorContext {
  projectName: string;
  projectVersion: string;
  currentYear: string;
}

/** Generate package.json content */
export const generatePackageJson = (ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      name: ctx.projectName,
      version: ctx.projectVersion,
      type: 'module',
      description: `${ctx.projectName} — Ink + React CLI application`,
      main: 'dist/cli.js',
      scripts: {
        build: 'tsc',
        dev: 'tsc --watch',
        start: 'node dist/cli.js',
        test: 'vitest run',
        lint: 'biome check source/',
        format: 'biome format --write source/',
        check: 'biome check --apply source/',
        typecheck: 'tsc --noEmit',
      },
      dependencies: {
        ink: '^7.1.0',
        react: '^19.0.0',
      },
      devDependencies: {
        '@biomejs/biome': '^2.5.0',
        '@types/react': '^19.0.0',
        lefthook: '^2.1.0',
        typescript: '^5.8.0',
        vitest: '^4.1.0',
      },
      engines: {
        node: '>=18.0.0',
      },
      files: ['dist/'],
    },
    null,
    2,
  );
};

/** Generate tsconfig.json content */
export const generateTsconfig = (_ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        outDir: 'dist',
        rootDir: 'source',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        jsx: 'react-jsx',
        jsxImportSource: 'react',
        resolveJsonModule: true,
        isolatedModules: true,
      },
      include: ['source/**/*.ts', 'source/**/*.tsx'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  );
};

/** Generate biome.json content */
export const generateBiomeJson = (_ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      $schema: 'https://biomejs.dev/schemas/2.5.5/schema.json',
      assist: {
        enabled: true,
        actions: {
          source: {
            organizeImports: true,
          },
        },
      },
      linter: {
        enabled: true,
        rules: { preset: 'recommended' },
      },
      formatter: {
        enabled: true,
        indentStyle: 'space',
        indentWidth: 2,
        lineWidth: 100,
      },
      javascript: {
        formatter: {
          quoteStyle: 'single',
          trailingCommas: 'all',
        },
      },
    },
    null,
    2,
  );
};

/** Generate lefthook.yml content */
export const generateLefthookYml = (_ctx: GeneratorContext): string => {
  return [
    '# Auto-generated by create-ink-app',
    'pre-commit:',
    '  parallel: true',
    '  commands:',
    '    typecheck:',
    '      run: npx tsc --noEmit',
    '    lint:',
    '      run: npx biome check source/',
    '    format:',
    '      run: npx biome format --write source/',
    '',
  ].join('\n');
};

/** Generate compat.json content */
export const generateCompatJson = (ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      scaffoldVersion: ctx.projectVersion,
      createdAt: new Date().toISOString(),
      generator: 'create-ink-app',
    },
    null,
    2,
  );
};

/** Generate .gitignore content */
export const generateGitignore = (_ctx: GeneratorContext): string => {
  return [
    '# Dependencies',
    'node_modules/',
    '',
    '# Build output',
    'dist/',
    'build/',
    '',
    '# Environment',
    '.env',
    '.env.local',
    '',
    '# OS files',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Editor',
    '*.swp',
    '*.swo',
    '*~',
    '',
    '# Test coverage',
    'coverage/',
    '',
  ].join('\n');
};

/** Generate .editorconfig content */
export const generateEditorconfig = (_ctx: GeneratorContext): string => {
  return [
    'root = true',
    '',
    '[*]',
    'indent_style = space',
    'indent_size = 2',
    'end_of_line = lf',
    'charset = utf-8',
    'trim_trailing_whitespace = true',
    'insert_final_newline = true',
    '',
    '[*.md]',
    'trim_trailing_whitespace = false',
    '',
  ].join('\n');
};

/** Generate readme.md content */
export const generateReadme = (ctx: GeneratorContext): string => {
  return [
    `# ${ctx.projectName}`,
    '',
    'An Ink + React CLI application scaffolded by create-ink-app.',
    '',
    '## Getting Started',
    '',
    '```sh',
    '# Install dependencies',
    'npm install',
    '',
    '# Run in development mode',
    'npm run dev',
    '',
    '# Build for production',
    'npm run build',
    '',
    '# Start the CLI',
    'npm start',
    '```',
    '',
    '## Available Scripts',
    '',
    '- `npm run build` — Compile TypeScript to `dist/`',
    '- `npm run dev` — Watch mode for development',
    '- `npm start` — Run the CLI application',
    '- `npm test` — Run tests with Vitest',
    '- `npm run lint` — Lint source code with Biome',
    '- `npm run format` — Format source code with Biome',
    '- `npm run check` — Apply lint fixes',
    '- `npm run typecheck` — Type-check without emitting files',
    '',
    '## License',
    '',
    `MIT © ${ctx.currentYear}`,
  ].join('\n');
};

/** Generate LICENSE content (MIT) */
export const generateLicense = (ctx: GeneratorContext): string => {
  const year = ctx.currentYear;
  return [
    'MIT License',
    '',
    `Copyright (c) ${year} ${ctx.projectName}`,
    '',
    'Permission is hereby granted, free of charge, to any person obtaining a copy',
    'of this software and associated documentation files (the "Software"), to deal',
    'in the Software without restriction, including without limitation the rights',
    'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
    'copies of the Software, and to permit persons to whom the Software is',
    'furnished to do so, subject to the following conditions:',
    '',
    'The above copyright notice and this permission notice shall be included in all',
    'copies or substantial portions of the Software.',
    '',
    'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
    'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
    'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
    'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
    'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM',
    'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE',
    'SOFTWARE.',
  ].join('\n');
};
