/**
 * Config generators — pure functions that produce configuration content
 * for each generated file in the scaffolded project.
 *
 * These live in the application layer because they orchestrate domain concepts
 * (project name, runtime, language) into concrete output.
 */

import type { Language, Linter, PreCommit, Runtime, TestFramework } from '@/shared/types';

export interface GeneratorContext {
  projectName: string;
  projectVersion: string;
  currentYear: string;
  runtime: Runtime;
  language: Language;
  linter: Linter;
  preCommit: PreCommit;
  testFramework: TestFramework;
}

/** Generate package.json content — context-aware */
export const generatePackageJson = (ctx: GeneratorContext): string => {
  const isBun = ctx.runtime === 'bun';

  const scripts: Record<string, string> = {};

  if (isBun) {
    // Bun runtime — use bun-native commands
    scripts.build = `bun build --target=node --outdir=dist source/cli.${ctx.language === 'typescript' ? 'tsx' : 'jsx'}`;
    scripts.dev = `bun --watch source/cli.${ctx.language === 'typescript' ? 'tsx' : 'jsx'}`;
    scripts.start = 'bun dist/cli.js';
    scripts.test = 'bun test';
  } else {
    // Node runtime
    scripts.build =
      ctx.language === 'typescript'
        ? 'tsc'
        : 'bun build --target=node --outdir=dist source/cli.jsx';
    scripts.dev = ctx.language === 'typescript' ? 'tsc --watch' : 'bun --watch source/cli.jsx';
    scripts.start = 'node dist/cli.js';
    scripts.test = 'vitest run';
  }

  // TypeScript-specific scripts
  if (ctx.language === 'typescript') {
    scripts.typecheck = 'tsc --noEmit';
  }

  // Linter-specific scripts
  if (ctx.linter === 'biome') {
    scripts.lint = 'biome check source/';
    scripts.format = 'biome format --write source/';
    scripts.check = 'biome check --write source/';
  } else if (ctx.linter === 'eslint-prettier') {
    scripts.lint = 'eslint source/';
    scripts.format = 'prettier --write source/';
    scripts.check = 'eslint source/ --fix';
  }

  const devDependencies: Record<string, string> = {};

  // Language-specific devDeps
  if (ctx.language === 'typescript') {
    devDependencies.typescript = '^5.8.0';
    devDependencies['@types/react'] = '^19.0.0';
  }

  // Linter-specific devDeps
  if (ctx.linter === 'biome') {
    devDependencies['@biomejs/biome'] = '^2.5.0';
  } else if (ctx.linter === 'eslint-prettier') {
    devDependencies.eslint = '^9.0.0';
    devDependencies.prettier = '^3.5.0';
  }

  // Pre-commit-specific devDeps
  if (ctx.preCommit === 'lefthook') {
    devDependencies.lefthook = '^2.1.0';
  } else if (ctx.preCommit === 'husky') {
    devDependencies.husky = '^9.0.0';
  }

  // Test framework devDeps — Bun uses built-in test runner, no vitest needed
  if (!isBun) {
    devDependencies.vitest = '^4.1.0';
  }

  return JSON.stringify(
    {
      name: ctx.projectName,
      version: ctx.projectVersion,
      type: 'module',
      description: `${ctx.projectName} — Ink + React CLI application`,
      main: 'dist/cli.js',
      scripts,
      dependencies: {
        ink: '^7.1.0',
        react: '^19.0.0',
      },
      devDependencies,
      engines: {
        node: '>=18.0.0',
      },
      files: ['dist/'],
    },
    null,
    2,
  );
};

/** Generate tsconfig.json content */
export const generateTsconfig = (_ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        outDir: 'dist',
        rootDir: 'source',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        jsx: 'react-jsx',
        jsxImportSource: 'react',
        resolveJsonModule: true,
        isolatedModules: true,
      },
      include: ['source/**/*.ts', 'source/**/*.tsx'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  );
};

/** Generate biome.json content */
export const generateBiomeJson = (_ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      $schema: 'https://biomejs.dev/schemas/2.5.5/schema.json',
      assist: {
        enabled: true,
        actions: {
          source: {
            organizeImports: true,
          },
        },
      },
      linter: {
        enabled: true,
        rules: { preset: 'recommended' },
      },
      formatter: {
        enabled: true,
        indentStyle: 'space',
        indentWidth: 2,
        lineWidth: 100,
      },
      javascript: {
        formatter: {
          quoteStyle: 'single',
          trailingCommas: 'all',
        },
      },
    },
    null,
    2,
  );
};

/** Generate lefthook.yml content */
export const generateLefthookYml = (ctx: GeneratorContext): string => {
  const pm = ctx.runtime === 'bun' ? 'bun' : 'npm';
  return [
    '# Auto-generated by create-ink-app',
    'pre-commit:',
    '  parallel: true',
    '  commands:',
    '    typecheck:',
    `      run: ${pm} run typecheck`,
    '    lint:',
    `      run: ${pm} run lint`,
    '    format:',
    `      run: ${pm} run format`,
    '',
  ].join('\n');
};

/** Generate compat.json content */
export const generateCompatJson = (ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      scaffoldVersion: ctx.projectVersion,
      createdAt: new Date().toISOString(),
      generator: 'create-ink-app',
    },
    null,
    2,
  );
};

/** Generate .gitignore content */
export const generateGitignore = (ctx: GeneratorContext): string => {
  const lines: string[] = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Build output',
    'dist/',
    'build/',
    '',
  ];

  // Bun lockfile
  if (ctx.runtime === 'bun') {
    lines.push('bun.lock');
    lines.push('');
  }

  lines.push(
    '# Environment',
    '.env',
    '.env.local',
    '',
    '# OS files',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Editor',
    '*.swp',
    '*.swo',
    '*~',
    '',
    '# Test coverage',
    'coverage/',
    '',
  );

  return lines.join('\n');
};

/** Generate .editorconfig content */
export const generateEditorconfig = (_ctx: GeneratorContext): string => {
  return [
    'root = true',
    '',
    '[*]',
    'indent_style = space',
    'indent_size = 2',
    'end_of_line = lf',
    'charset = utf-8',
    'trim_trailing_whitespace = true',
    'insert_final_newline = true',
    '',
    '[*.md]',
    'trim_trailing_whitespace = false',
    '',
  ].join('\n');
};

/** Generate readme.md content */
export const generateReadme = (ctx: GeneratorContext): string => {
  const isBun = ctx.runtime === 'bun';
  const pm = isBun ? 'bun' : 'npm';

  const lines: string[] = [
    `# ${ctx.projectName}`,
    '',
    'An Ink + React CLI application scaffolded by create-ink-app.',
    '',
    '## Getting Started',
    '',
    '```sh',
    '# Install dependencies',
    `${pm} install`,
    '',
    '# Run in development mode',
    `${pm} run dev`,
    '',
    '# Build for production',
    `${pm} run build`,
    '',
    '# Start the CLI',
    `${pm} start`,
    '```',
    '',
    '## Available Scripts',
    '',
    `- \`${pm} run build\` — Compile to \`dist/\``,
    `- \`${pm} run dev\` — Watch mode for development`,
    `- \`${pm} start\` — Run the CLI application`,
    isBun ? '- `bun test` — Run tests with Bun' : '- `npm test` — Run tests with Vitest',
  ];

  if (ctx.linter === 'biome') {
    lines.push(`- \`${pm} run lint\` — Lint source code with Biome`);
    lines.push(`- \`${pm} run format\` — Format source code with Biome`);
    lines.push(`- \`${pm} run check\` — Apply lint fixes`);
  } else if (ctx.linter === 'eslint-prettier') {
    lines.push(`- \`${pm} run lint\` — Lint source code with ESLint`);
    lines.push(`- \`${pm} run format\` — Format source code with Prettier`);
    lines.push(`- \`${pm} run check\` — Apply lint fixes`);
  }

  if (ctx.language === 'typescript') {
    lines.push(`- \`${pm} run typecheck\` — Type-check without emitting files`);
  }

  lines.push('', '## License', '', `MIT © ${ctx.currentYear}`);

  return lines.join('\n');
};

/** Generate LICENSE content (MIT) */
export const generateLicense = (ctx: GeneratorContext): string => {
  const year = ctx.currentYear;
  return [
    'MIT License',
    '',
    `Copyright (c) ${year} ${ctx.projectName}`,
    '',
    'Permission is hereby granted, free of charge, to any person obtaining a copy',
    'of this software and associated documentation files (the "Software"), to deal',
    'in the Software without restriction, including without limitation the rights',
    'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
    'copies of the Software, and to permit persons to whom the Software is',
    'furnished to do so, subject to the following conditions:',
    '',
    'The above copyright notice and this permission notice shall be included in all',
    'copies or substantial portions of the Software.',
    '',
    'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
    'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
    'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
    'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
    'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM',
    'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE',
    'SOFTWARE.',
  ].join('\n');
};

/** Generate eslint.config.js flat config content */
export const generateEslintConfig = (_ctx: GeneratorContext): string => {
  return [
    '// Auto-generated by create-ink-app',
    'export default [',
    '  {',
    '    rules: {',
    '      semi: ["error", "always"],',
    '      quotes: ["error", "single"],',
    '      "no-unused-vars": "warn",',
    '      "no-console": "off",',
    '    },',
    '    ignores: ["dist/"],',
    '  },',
    '];',
    '',
  ].join('\n');
};

/** Generate .prettierrc content */
export const generatePrettierrc = (_ctx: GeneratorContext): string => {
  return JSON.stringify(
    {
      semi: true,
      singleQuote: true,
      trailingComma: 'all',
      printWidth: 100,
      tabWidth: 2,
    },
    null,
    2,
  );
};

/** Generate .husky/pre-commit hook content */
export const generateHuskyHook = (ctx: GeneratorContext): string => {
  const pm = ctx.runtime === 'bun' ? 'bun' : 'npm';
  return ['#!/usr/bin/env sh', '. "$(dirname -- "$0")/_/husky.sh"', '', `${pm} test`, ''].join(
    '\n',
  );
};

/** Generate vitest.config.ts content */
export const generateVitestConfig = (_ctx: GeneratorContext): string => {
  return [
    "import { defineConfig } from 'vitest/config';",
    '',
    'export default defineConfig({',
    '  test: {',
    '    environment: "node",',
    '  },',
    '});',
    '',
  ].join('\n');
};
